SET SESSION FOREIGN_KEY_CHECKS=0;

/* Create Tables */

CREATE TABLE INFO
(
	INFO_ID bigint NOT NULL AUTO_INCREMENT,
	MEMBER_ID bigint NOT NULL,
	INFO_NAME varchar(256) NOT NULL,
	PRIMARY KEY (INFO_ID)
);


CREATE TABLE MEMBER
(
	MEMBER_ID bigint NOT NULL AUTO_INCREMENT,
	NAME varchar(64) NOT NULL,
	PASSWORD varchar(128) NOT NULL,
	PRIMARY KEY (MEMBER_ID)
);



/* Create Foreign Keys */

ALTER TABLE INFO
	ADD FOREIGN KEY (MEMBER_ID)
	REFERENCES MEMBER (MEMBER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



